### ISSUE TITLE
Discord Rich Presence not working properly

### ISSUE THREAD

**Issue by Lemon4ksan** [TheKing-OfTime/YandexMusicModClient#10] opened 2024-08-10 10:28 UTC
After some time or by switching songs slightly faster, Rich Presence stops responding and freezes or disappears

![image](https://github.com/user-attachments/assets/d4a9e235-39a4-4a6e-bc38-095c0d5e2b4b)

Most of the time Discord doesn't recognise the app at all

![image](https://github.com/user-attachments/assets/f5e5a287-7a37-4d55-a948-1b15e37eec07)

The only way to fix this now, is to restart Yandex Music and Discord

 - OS: Windows 10 22H2
 - Yandex Music version: 5.10.2

**Comment by TheKing-OfTime** [comment] 2024-08-10 10:58
Thanks for your report. 
This bug was caused by the fix of another bug #7. I'll try to find more elegant solution in the next release.

**Comment by TheKing-OfTime** [comment] 2024-08-10 16:40
This issue should be fixed. Reopen if you encounter this bug again

**Closed by TheKing-OfTime** 2024-08-10 16:40 UTC
Labels: bug

**Comment by Lemon4ksan** [comment] 2024-08-10 16:55
Everything works fine, thanks for your fix!
